parola/data_tools/urls.py
from django.conf.urls import url

from . import views

app_name = 'data_tools'
urlpatterns = [
    url(r'^cpc_extractor/', views.cpc_extractor, name='cpc_extractor'),
    url(r'^co_occurrence/', views.co_occurrence, name='co_occurrence'),
    url(r'^new_category_set_keywords/', views.new_category_set_keywords, name='new_category_set_keywords'),
    url(r'^categorize_by_keywords/(?P<data_set>.*)/(?P<category_set>.*)/$', views.categorize_by_keywords, name='categorize_by_keywords'),
    url(r'^view_category_sets/', views.view_category_sets, name='view_category_sets'),
    url(r'^view_training_sets/', views.view_training_sets, name='view_training_sets'),
    url(r'^new_training_setup/', views.new_training_setup, name='new_training_setup'),
    url(r'^view/(?P<training_set>.*)/$', views.view_training_set, name='view_training_set'),
    url(r'^automated_patent_classification/(?P<data_set>.*)/(?P<training_set>.*)/$', views.automated_patent_classification, name='automated_patent_classification'),
    url(r'^input_classification_bar_graph/', views.input_classification_bar_graph, name='input_classification_bar_graph'),
    url(r'^input_classification_accuracy_bar_graph/', views.input_classification_accuracy_bar_graph, name='input_classification_accuracy_bar_graph'),
    url(r'^download_sample_cpc_extractor/', views.download_sample_cpc_extractor, name='download_sample_cpc_extractor'),
    url(r'^download_sample_co_occurrence/', views.download_sample_co_occurrence, name='download_sample_co_occurrence'),
    url(r'^download_cpc_extractor/', views.download_cpc_extractor, name='download_cpc_extractor'),
    url(r'^download_co_occurrence/', views.download_co_occurrence, name='download_co_occurrence'),
    url(r'^download_sample_category_keywords/', views.download_sample_category_keywords, name='download_sample_category_keywords'),
    url(r'^download_categorize_by_keywords/', views.download_categorize_by_keywords, name='download_categorize_by_keywords'),
    url(r'^download_classification/', views.download_classification, name='download_classification'),
    url(r'^download_tag_words/', views.download_tag_words, name='download_tag_words'),
]

parola/main/urls.py
from django.conf.urls import url

from . import views
from data_sets import views as data_sets_views
from uspto import views as uspto_views
from data_tools import views as data_tools_views
from parola_refine import views as parola_refine_views
from visualization import views as visualization_tools_views

app_name = 'main'
urlpatterns = [
    url(r'', views.index, name='index'),
    # url(r'^data_sets/new_data_setup', data_sets_views.new_data_setup, name='new_data_setup'),
    # url(r'^data_sets/view_data_sets', data_sets_views.view_data_sets, name='view_data_sets'),

    # url(r'^view_category_sets/(?P<category_set>.*)/$', data_tools_views.view_category_sets, name='view_category_sets'),
    # url(r'^new_category_set_keywords/', data_tools_views.new_category_set_keywords, name='new_category_set_keywords'),
    # url(r'^categorize_by_keywords/(?P<data_set>.*)/(?P<category_set>.*)/$', data_tools_views.categorize_by_keywords, name='categorize_by_keywords'),
    # url(r'^new_training_setup/', data_tools_views.new_training_setup, name='new_training_setup'),
    # url(r'^view/(?P<training_set>.*)/$', data_tools_views.view_training_set, name='view_training_set'),
    # url(r'^automated_patent_classification/(?P<data_set>.*)/(?P<training_set>.*)/$', data_tools_views.automated_patent_classification, name='automated_patent_classification'),
    # url(r'^reference_update', parola_refine_views.reference_update, name='reference_update'),
    # url(r'^assignee_grouping/(?P<data_set>.*)/$', parola_refine_views.assignee_grouping, name='assignee_grouping'),

    # url(r'^dataset_statistics/(?P<data_set>.*)/(?P<classification>.*)/$', visualization_tools_views.dataset_statistics, name='dataset_statistics'),
    # url(r'^category_statistics/(?P<data_set>.*)/(?P<classification>.*)/(?P<category>.*)/$', visualization_tools_views.category_statistics),
    # url(r'^assignee_statistics/(?P<data_set>.*)/(?P<classification>.*)/(?P<assignee>.*)/$', visualization_tools_views.assignee_statistics),
    # url(r'^cluster_map/(?P<data_set>.*)/(?P<classification1>.*)/(?P<classification2>.*)/$', visualization_tools_views.cluster_map, name='cluster_map'),
    # url(r'^landscape_map/(?P<data_set>.*)/$', visualization_tools_views.landscape_map, name='landscape_map'),
]

parola/parola/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('main.urls')),
    path('data_sets/', include('data_sets.urls')),
    path('data_tools/', include('data_tools.urls')),
    path('parola_refine/', include('parola_refine.urls')),
    path('visualization/', include('visualization.urls')),
    path('download_manager/', include('download_manager.urls')),
    path('admin/', admin.site.urls),
]

parola/data_tools/models.py
from django.db import models

# Create your models here.

parola/data_tools/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest
from wsgiref.util import FileWrapper
from django import forms
from django.template.loader import render_to_string

from data_sets.models import Patents
from data_sets.models import Datasets
from data_sets.models import TrainingDatasets
from data_sets.models import TrainingPatents
from data_sets.models import CategorySet
from data_sets.models import CategorySetKeywords

import datetime
import numpy as np
import pandas as pd
import os
import math
import ast

import DBQueries as dbq
import PatentProcessing as pp
import CategoriesCleaner as catc
import ClaimsCleaner as cc
import ItemSelector as ise

pd.options.display.max_colwidth = 1000

class UploadFileForm(forms.Form):
    file = forms.FileField()

# View for the list of data tools
def data_tools(request):
    return render(
        request,
        'data_tools/data_tools.html',
        {}
    )

# View for CPC and Descriptions Extractor
def cpc_extractor(request):
    errors = []
    warnings = []
    valid = False
    targetSheetName = None
    form = None
    columnList = None
    sampleFileHTML = None
    inputFileHTML = None
    CPCDescriptionsHTML = None

    inFileName = 'cpcExtractorInput'
    outFileName = 'CPC Nodes with Descriptions'
    inFolderName = '../in/'
    outFolderName = '../out/'
    fileType = '.xlsx'
    sheetName = 'Sheet1'
    
    # Submit File View Setup
    if(request.method == "POST" and request.POST.get('upload')): 
        form = UploadFileForm(request.POST, request.FILES)
        inputFile = request.FILES['file']
        if form.is_valid():
            inputFile = request.FILES['file']
            targetSheetName = request.POST.get('target-sheet')
            # TODO: Validate file
            # if(valid):
            # Read data from input excel file and save it as a dataframe
            inputFileDF = pd.read_excel(inputFile, targetSheetName)
            columnList = inputFileDF.columns
            inputFileDF.to_excel(inFolderName + inFileName + fileType, index=False)
            inputFileHTML = inputFileDF.to_html()
        try:       
            if(inputFile):
                inputFile.close()
        except Exception:
            valid = False
            errors.append("The process cannot access the input file because it is being used by another process.")
        valid = True

    # Process File View Setup
    elif(request.method == "POST" and request.POST.get('process')):
        targetColumnName = request.POST.get('target-column')
        # TODO: Get CPCs and descriptions from the database
        descriptionsDF = pd.read_excel('../out/CPC Descriptions.xlsx', sheetName)
        inputFileDF = pd.read_excel(inFolderName + inFileName + fileType, sheetName)
        outDF = pd.DataFrame()
        outDF = inputFileDF.copy()
        outDF['Descriptions'], outDF['CPC'] = pp.getCPCDescriptions(pd.DataFrame(outDF, columns=outDF.keys()), descriptionsDF, targetColumnName)
        CPCDescriptionsHTML = outDF.to_html()
        outDF.to_excel(outFolderName + outFileName + fileType)
    
    # Default View Setup
    else:
        form = UploadFileForm()
        sampleFileDF = pd.read_excel('../out/Sample File for CPC and Descriptions Extractor.xlsx', 'Sheet1')
        sampleFileHTML = sampleFileDF.to_html()

    return render(
        request,
        'data_tools/cpc_extractor.html',
        {
            'form': form,
            'valid': valid,
            'errors': errors,
            'warnings': warnings,
            'columnList': columnList,
            'sampleFileHTML': sampleFileHTML,
            'inputFileHTML': inputFileHTML,
            'CPCDescriptionsHTML': CPCDescriptionsHTML,
        }
    )

# View for Co-Occurrence Matrix Generator
def co_occurrence(request):
    errors = []
    warnings = []
    valid = False
    targetSheetName = None
    form = None
    columnList = None
    matrix = None
    sampleFileHTML = None
    inputFileHTML = None
    matrixHTML = None

    inFileName = 'coOccurrenceInput'
    outFileName = 'Co-Occurrence Matrix'
    inFolderName = '../in/'
    outFolderName = '../out/'
    fileType = '.xlsx'
    sheetName = 'Sheet1'

    # Submit File View Setup
    if(request.method == "POST" and request.POST.get('upload')): 
        form = UploadFileForm(request.POST, request.FILES)
        inputFile = request.FILES['file']
        if form.is_valid():
            inputFile = request.FILES['file']
            targetSheetName = request.POST.get('target-sheet')
            # TODO: Validate file
            # if(valid):
            # Read data from input excel file and save it as a dataframe
            inputFileDF = pd.read_excel(inputFile, targetSheetName)
            columnList = inputFileDF.columns
            inputFileDF.to_excel(inFolderName + inFileName + fileType, index=False)
            inputFileHTML = inputFileDF.to_html()
        try:       
            if(inputFile):
                inputFile.close()
        except Exception:
            valid = False
            errors.append("The process cannot access the input file because it is being used by another process.")
        valid = True

    # Submit File View
    elif(request.method == "POST" and request.POST.get('process')): 
        targetColumnName = request.POST.get('target-column')
        targetColumnType = request.POST.get('column-type')
        # TODO: Validate file
        df = pd.read_excel(inFolderName + inFileName + fileType, sheetName)
        if(targetColumnType == 'category'):
            df['cleanCategories'] = catc.getCleanL1L2L3Categories(df[targetColumnName])
            categories = df['cleanCategories'].tolist()
        elif(targetColumnType == 'cpc'):
            df['cleanCPCs'], df['cleanCPC4s'] = cc.getCPCs(df[targetColumnName])
            categories = df['cleanCPCs'].tolist()

        allCategories = []
        categoryList = []

        for cList in categories:
            if(cList and cList == cList):
                categoryList.append(cList)

        for cList in categories:
            if(cList and cList == cList):
                # for c in ast.literal_eval(cList):
                for c in cList:
                    allCategories.append(c)
        uniqueCategories = set(allCategories)

        matrix = pd.DataFrame(columns=uniqueCategories, index=uniqueCategories)
        for a in uniqueCategories:
            for b in uniqueCategories:
                count = 0
                for x in categoryList:
                    if a != b:
                        if a in x and b in x:
                            count += 1
                    else:
                        n = x.count(a)
                        if n >= 2:
                            count += math.factorial(n)/math.factorial(n - 2)/2
                matrix.at[a, b] = count

        matrix = matrix.reset_index()
        matrix.to_excel(outFolderName + outFileName + fileType, index=False)
        matrixHTML = matrix.to_html()

    # Default View
    else:
        form = UploadFileForm()
        sampleFileDF = pd.read_excel('../out/Sample File for Co-Occurrence Matrix.xlsx', 'Sheet1')
        sampleFileHTML = sampleFileDF.to_html()

    return render(
        request,
        'data_tools/co_occurrence.html',
        {
            'form': form,
            'valid': valid,
            'errors': errors,
            'warnings': warnings,
            'columnList': columnList,
            'sampleFileHTML': sampleFileHTML,
            'inputFileHTML': inputFileHTML,
            'matrixHTML': matrixHTML,
        }
    )

# View for updating category keywords
def new_category_set_keywords(request):
    form = None
    errors = []
    warnings = []
    valid = False
    hasInputFile = False
    targetSheetName = None
    columnList = None
    data_set = 'index'
    inFolderName = '../in/'
    inFileName = 'newCategorySetInput'
    fileType = '.xlsx'

    # Submit File View Setup
    if(request.method == "POST" and request.POST.get('upload')):  
        form = UploadFileForm(request.POST, request.FILES)
        inputFile = request.FILES['file']
        if form.is_valid():
            inputFile = request.FILES['file']
            targetSheetName = request.POST.get('target-sheet')
            inputFileDF = pd.read_excel(inputFile, targetSheetName)
            columnList = list(inputFileDF.columns)
            inputFileDF.to_excel(inFolderName + inFileName + fileType, index=False)
        try:       
            if(inputFile):
                inputFile.close()
        except Exception:
            valid = False
            errors.append("The process cannot access the input file because it is being used by another process.")
        hasInputFile = True

    # Step 2 View
    elif(request.method == "POST" and request.POST.get('finish')): 
        categorySetName = request.POST.get('category-set-name')
        targetCategoryColumnName = request.POST.get('target-column-category')
        targetKeywordsColumnName = request.POST.get('target-column-keywords')
        df = pd.read_excel(inFolderName + inFileName + fileType, 'Sheet1')
        df = df.rename(index=str, columns={
            targetCategoryColumnName: "Category", 
            targetKeywordsColumnName: "Keywords", 
            })
        dbq.insertCategoryKeywords(df, categorySetName)
        hasInputFile = True
        valid = True
    
        dataSetNames = []
        datasets = Datasets.objects.all()
        for dataset in datasets:
            dataSetNames.append(dataset.name)
        dataSetNames.insert(0, 'index')

        categorySetNames = []
        categorySets = CategorySet.objects.all()
        for categorySet in categorySets:
            categorySetNames.append(categorySet.name)

        templateHTML = 'data_tools/view_category_sets.html'
        mainHTML = render_to_string(
            templateHTML, {
            'valid': valid,
            'errors': errors,

parola/templates/data_tools/automated_patent_classification.html
<div class="col shadow p-3 mb-5 bg-white rounded">
    <div>
        <h3>Automated Patent Classification</h3>
    </div>
    {% if hasDataSet or valid %}
    <div>
        <a href="/data_tools/automated_patent_classification/index/index"> << Start over </a>
    </div>
    {% endif %}

    {% if not hasDataSet %}
    <div>
        <h4>Step 1. Select a data set and a training set</h4>
    </div>
    <div>
        <form action="" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <table class="form-text">
            <tr>
                <td class="label"><label class="control-label">Data Set: </label></td>
                <td>
                    <select class="form-control" onChange="window.location.href=this.value">
                        {% for dataSet in dataSetNames %}
                        {% if dataSet == 'index' %}
                        <option selected="selected" disabled>Choose one</option>
                        {% elif data_set == dataSet %}
                        <option selected="selected" value="/data_tools/automated_patent_classification/{{dataSet}}/{{training_set}}">{{data_set}}</option>
                        {% else %}
                        <option value="/data_tools/automated_patent_classification/{{dataSet}}/{{training_set}}">{{dataSet}}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <td class="label"><label class="control-label">Training Set: </label></td>
                <td>
                    <select class="form-control" onChange="window.location.href=this.value">
                        {% for trainingSet in trainingDataSetNames %}
                        {% if trainingSet == 'index' %}
                        <option selected="selected" disabled>Choose one</option>
                        {% elif training_set == trainingSet %}
                        <option selected="selected" value="/data_tools/automated_patent_classification/{{data_set}}/{{trainingSet}}">{{training_set}}</option>
                        {% else %}
                        <option value="/data_tools/automated_patent_classification/{{data_set}}/{{trainingSet}}">{{trainingSet}}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </td>
            </tr>
        </table>
        </form>
    </div>
    {% endif %}

    {% if hasDataSet and not valid %}
    <div>
        <h4>Step 2. Setup the classification model</h4>
    </div>
    <div>
        <form action="" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <table class="form-text">
            <tr>
                <td class="label"><label class="control-label">Features: </label></td>
                <td><input type="checkbox" name="features" value="titles" checked="checked">Titles</td>
            </tr>
            <tr>
                <td class="label"><label class="control-label"></label></td>
                <td><input type="checkbox" name="features" value="abstracts" checked="checked">Abstracts</td>
            </tr>
            <tr>
                <td class="label"><label class="control-label"></label></td>
                <td><input type="checkbox" name="features" value="independentclaims" checked="checked">Independent Claims</td>
            </tr>
            <tr>
                <td class="label"><label class="control-label">Method: </label></td>
                <td>
                    <input type="radio" name="method" value="gradientboosting" checked="checked"> Gradient Boosting <br>
                    <input type="radio" name="method" value="mlpclassifier"> Multi-layer Perceptron <br>
                    <input type="radio" name="method" value="randomforest"> Random Forest <br>
                </td>
            </tr>
            <tr>
                <td class="label"><label class="control-label">Test Size: </label></td>
                <td>
                    <input class="form-control" class="target-test-size" type="number" value="0.2" step="0.01" name="target-test-size">
                </td>
            </tr>             
            <tr>
                <td class="label"><label class="control-label">Number of Estimators: </label></td>
                <td>
                    <input class="form-control" type="number" value="500"name="target-n-estimator">
                </td>
            </tr>             
            <tr>
                <td class="label"><label class="control-label">Learning Rate: </label></td>
                <td>
                    <input class="form-control" type="number" value="0.05" step="0.01" name="target-learning-rate">
                </td>
            </tr>              
            <tr>
                <td class="label"><label class="control-label">N-Gram Range: </label></td>
                <td>
                    <input class="form-control" type="number" value="1" name="target-n-gram-1">
                </td>
                <td>
                    <input class="form-control" type="number" value="2" name="target-n-gram-2">
                </td>
            </tr>                
            <tr>
                <td class="label"><label class="control-label"></label></td>
                <td>
                    <input class="btn btn-info" type="submit" value="Process" name="process">
                </td>
            </tr>
        </table>
        </form>
    </div>
    {% endif %}
</div>


{% if valid %}
<div class="col shadow p-3 mb-5 bg-white rounded">
    <div>
        <h4>Prediction Counts</h4>
    </div>
    <div>
        <svg width="960" height="400" id="bar-svg"></svg>
        <script>
            var svg = d3v4.select("#bar-svg"),
                margin = {top: 20, right: 20, bottom: 30, left: 240},
                width = +svg.attr("width") - margin.left - margin.right,
                height = +svg.attr("height") - margin.top - margin.bottom,
                barG = svg.append("g").attr("transform", "translate(" + margin.left + "," + margin.top + ")");

            var barY = d3v4.scaleBand()	
                .rangeRound([0, height])
                .paddingInner(0.05)
                .align(0.1);

            var barX = d3v4.scaleLinear()
                .rangeRound([0, width]);
                
            var barZ = d3v4.scaleOrdinal(d3v4.schemeCategory10);
            var colors = ["#5BEEFF", "#173B40", "#51D6E5", "#44B2BF", "#2D777F", "#e5f2f9", "#E9EDDE", "#e2e2e2"]

            d3v4.tsv("{% url 'data_tools:input_classification_bar_graph' %}", function(d, i, columns) {
            for (i = 1, t = 0; i < columns.length; ++i) t += d[columns[i]] = +d[columns[i]];
            d.total = t;
            return d;
            }, function(error, data) {
                
            if (error) throw error;

            var keys = data.columns.slice(1);

            data.sort(function(a, b) { return b.total - a.total; });
            barY.domain(data.map(function(d) { return d.classification; }));
            barX.domain([0, d3v4.max(data, function(d) { return d.total; })]).nice();
            barZ.domain(keys);

            barG.append("g")
                .selectAll("g")
                .data(d3v4.stack().keys(keys)(data))
                .enter().append("g")
                .attr("fill", "#2D777F")
                .attr("transform", "translate(0,"+margin.top+")")
                .selectAll("rect")
                .data(function(d) { return d; })
                .enter().append("rect")
                .attr("class", "bar")
                .attr("y", function(d) { return barY(d.data.classification); })
                .attr("x", function(d) { return barX(d[0]); })
                .attr("width", function(d) { return barX(d[1]) - barX(d[0]); })
                .attr("height", barY.bandwidth());

            barG.append("g")
                .attr("class", "axis")
                .attr("transform", "translate(0,"+margin.top+")")
                .call(d3v4.axisLeft(barY));

            barG.append("g")
                .attr("class", "axis")
                .attr("transform", "translate(0,0)")
                .call(d3v4.axisBottom(barX).ticks(null).tickSize(0))
                .append("text")
                .attr("y", 0)
                .attr("x", barX(barX.ticks().pop()) - 1)
                .attr("dy", "0.32em")
                .attr("fill", "#000")
                .attr("text-anchor", "start")
                .text("Number of P/PA")
                .attr("transform", "translate("+ (-width) +",-10)");
            });
        </script>
    </div>
</div>
{% endif %}

<div class="col shadow p-3 mb-5 bg-white rounded">
{% if classificationHTML and testCorrectness %}
    <div>
        <h4>Prediction Accuracies</h4>
    </div>
    <div>
        <svg width="960" height="400" id="abar-svg"></svg>
        <script>
            var svg = d3v4.select("#abar-svg"),
                margin = {top: 20, right: 20, bottom: 30, left: 240},
                width = +svg.attr("width") - margin.left - margin.right,
                height = +svg.attr("height") - margin.top - margin.bottom,
                abarG = svg.append("g").attr("transform", "translate(" + margin.left + "," + margin.top + ")");

            var abarY = d3v4.scaleBand()	
                .rangeRound([0, height])
                .paddingInner(0.05)
                .align(0.1);

            var abarX = d3v4.scaleLinear()
                .rangeRound([0, width]);
                
            var abarZ = d3v4.scaleOrdinal(d3v4.schemeCategory10);
            var colors = ["#5BEEFF", "#173B40", "#51D6E5", "#44B2BF", "#2D777F", "#e5f2f9", "#E9EDDE", "#e2e2e2"]

            d3v4.tsv("{% url 'data_tools:input_classification_accuracy_bar_graph' %}", function(d, i, columns) {
            for (i = 1, t = 0; i < columns.length; ++i) t += d[columns[i]] = +d[columns[i]];
            d.total = t;
            return d;
            }, function(error, data) {
                
            if (error) throw error;

            var keys = data.columns.slice(1);

            data.sort(function(a, b) { return b.total - a.total; });
            abarY.domain(data.map(function(d) { return d.index; }));
            abarX.domain([0, d3v4.max(data, function(d) { return d.total; })]).nice();
            abarZ.domain(keys);

            abarG.append("g")
                .selectAll("g")
                .data(d3v4.stack().keys(keys)(data))
                .enter().append("g")
                .attr("fill", "#2D777F")
                .attr("transform", "translate(0,"+margin.top+")")
                .selectAll("rect")
                .data(function(d) { return d; })
                .enter().append("rect")
                .attr("class", "bar")
                .attr("y", function(d) { return abarY(d.data.index); })
                .attr("x", function(d) { return abarX(d[0]); })
                .attr("width", function(d) { return abarX(d[1]) - abarX(d[0]); })
                .attr("height", abarY.bandwidth());

            abarG.append("g")
                .attr("class", "axis")
                .attr("transform", "translate(0,"+margin.top+")")
                .call(d3v4.axisLeft(abarY));

            abarG.append("g")
                .attr("class", "axis")
                .attr("transform", "translate(0,0)")
                .call(d3v4.axisBottom(abarX).ticks(null).tickSize(0))
                .append("text")
                .attr("y", 0)
                .attr("x", abarX(abarX.ticks().pop()) - 1)
                .attr("dy", "0.32em")
                .attr("fill", "#000")
                .attr("text-anchor", "start")
                .text("Number of P/PA")
                .attr("transform", "translate("+ (-width) +",-10)");
            });
        </script>
    </div>
</div>
{% endif %}

<!-- View of Tag Words File -->
{% if tagWordsHTML %}
<div class="col shadow p-3 mb-5 bg-white rounded">
    <div>
        <h4>Tag Words</h4>
    </div>
    <div class="scroll-vertical">
        {{tagWordsHTML | safe}}
    </div>
    <a href="/data_tools/download_tag_words"> Download Table </a>
</div>
{% endif %}

<!-- View of Train Accuracies -->
{% if trainConfusionMatrixHTML %}
<div class="col shadow p-3 mb-5 bg-white rounded">
    <div>
        <h4>Train Accuracy</h4>
    </div>
    <div>
        <h5>Overall Train Accuracy: {{trainCorrectness}}</h5>
    </div>
    <div>
        <h5>Classification Accuracies:</h5>
    </div>
    <div class="scroll-vertical">
        {{trainConfusionMatrixHTML | safe}}
    </div>
</div>
{% endif %}
    
<!-- View of Test Accuracies-->
{% if testConfusionMatrixHTML %}
<div class="col shadow p-3 mb-5 bg-white rounded">
    <div>
        <h4>Test Accuracy</h4>
    </div>
    <div>
        <h5>Overall Test Accuracy: {{testCorrectness}}</h5>
    </div>
    <div>
        <h5>Classification Accuracies:</h5>
    </div>
    <div class="scroll-vertical">
    {{testConfusionMatrixHTML | safe}}
    </div>
</div>
{% endif %}

<!-- View of Classifications-->
{% if classificationHTML %}
<div class="col shadow p-3 mb-5 bg-white rounded">
    <div>
        <h4>Results</h4>
    </div>
    <div class="scroll-both">
        {{ classificationHTML | safe }}
    </div>
    <a href="/data_tools/download_classification"> Download Table </a>
</div>
{% endif %}

parola/templates/data_tools/categorize_by_keywords.html
<div class="col shadow p-3 mb-5 bg-white rounded">
    <div>
        <h3>Categorize by Keywords</h3>
    </div>
    <div>
        <table class="form-text">
            <tr>
                <td class="label"><label class="control-label">Data Set: </label></td>
                <td>
                    <select class="form-control" onChange="window.location.href=this.value">
                        {% for dataSet in dataSetNames %}
                        {% if dataSet == 'index' %}
                        <option selected="selected" disabled value="/data_tools/categorize_by_keywords/index/index">Choose one</option>
                        {% elif data_set == dataSet %}
                        <option selected="selected" value="/data_tools/categorize_by_keywords/{{data_set}}/{{category_set}}">{{data_set}}</option>
                        {% else %}
                        <option value="/data_tools/categorize_by_keywords/{{dataSet}}/{{category_set}}">{{dataSet}}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <td class="label"><label class="control-label">Category Set: </label></td>
                <td>
                    <select class="form-control" onChange="window.location.href=this.value">
                        {% for categorySet in categorySetNames %}
                        {% if categorySet == 'index' %}
                        <option selected="selected" disabled>Choose one</option>
                        {% elif category_set == categorySet %}
                        <option selected="selected" value="/data_tools/categorize_by_keywords/{{data_set}}/{{categorySet}}">{{categorySet}}</option>
                        {% else %}
                        <option value="/data_tools/categorize_by_keywords/{{data_set}}/{{categorySet}}">{{categorySet}}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <form action="" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <tr>
                <td class="label"><label class="control-label">Features: </label></td>
                <td><input type="checkbox" name="features" value="titles" checked="checked">Titles</td>
            </tr>
            <tr>
                <td class="label"><label class="control-label"></label></td>
                <td><input type="checkbox" name="features" value="abstracts" checked="checked">Abstracts</td>
            </tr>
            <tr>
                <td class="label"><label class="control-label"></label></td>
                <td><input type="checkbox" name="features" value="independentclaims" checked="checked">Independent Claims</td>
            </tr>
            {% if hasDataSet and hasCategorySet %}
            <tr>
                <td class="label"><label class="control-label"></label></td>
                <td>
                    <input class="btn btn-info" type="submit" value="Process" name="process">
                </td>
            </tr>
            </form>
            {% endif %}
        </table>
    </div>

    {% if valid %}
    <div>
        <a href="/visualization/dataset_statistics/{{data_set}}/category_by_keywords">Check results here</a>
    </div>
    {% endif %}
</div>